add GetListAsync filter template
EasyAbp/AbpHelper.CLI pull request #189
Opened 2022-09-29 09:09 UTC by blackWins

Check _**Extension PagedAndSortedResultRequestDto**_ generate filter input

![image](https://user-images.githubusercontent.com/34080651/192989950-2d9c6592-217e-4294-a535-54ac61ab3ad2.png)
![image](https://user-images.githubusercontent.com/34080651/192990162-4f05419b-de4b-4867-9994-ed8506b89a9d.png)

2022-10-07 04:18 UTC, blackWins commented
filter area added Collapse effect

![image](https://user-images.githubusercontent.com/34080651/194466915-651b26a0-f576-4c91-beea-da70b94dc3ae.png)

2022-10-22 10:30 UTC, gdlcf88 commented
@blackWins - Could you please add "TableFilter" localization items?

2022-10-22 10:33 UTC, gdlcf88 requested changes

2022-10-22 10:33 UTC, gdlcf88 commented on src/AbpHelper.Core/Templates/Crud/Groups/Service/src/{{ProjectInfo.FullName}}.Application.Contracts/{{EntityInfo.RelativeDirectory}}/Dtos/{{ EntityInfo.Name }}GetListInput.cs
> +    public {{ prop.Type}}{{- if prop.Type!="string";"?";end}} {{ prop.Name }} { get; set; }
There should be a new line between the properties.

2022-10-30 08:31 UTC, gdlcf88 approved these changes

2022-10-30 08:31 UTC, merged